import type { RawTypesConfig } from "@graphql-codegen/visitor-plugin-common";

export type RawConfig = {
    /**
     * path to type definitions file
     * this is generated by client preset
     * e.g. ) "typeFile: "./graphql"
     */
    typesFile?: string | undefined;
    skipTypename?: RawTypesConfig["skipTypename"] | undefined;
    namingConvention?: RawTypesConfig["namingConvention"] | undefined;
    typesPrefix?: RawTypesConfig["typesPrefix"] | undefined;
    typesSuffix?: RawTypesConfig["typesSuffix"] | undefined;
    maxFieldRecursionDepth?: number | undefined;
    defaultValues?:
        | {
              String?: string | undefined;
              Int?: number | undefined;
              Float?: number | undefined;
              Boolean?: boolean | undefined;
              ID?: string | undefined;
              listLength?: number | undefined;
              CustomScalar?: {
                  /**
                   * CustomScalar default expression
                   * The value must be an JavaScript expression.
                   * If you want to put a string value, you must put it in quotes
                   * @example
                   * ```js
                   * CustomScalar: {
                   *   Digit: "1",
                   *   DateYYYYMMDD: "'2022-02-03'",
                   *   ISODateTime: "new Date().toISOString()"
                   * }
                   * ```
                   */
                  [key: string]: string;
              };
          }
        | undefined;
};

export const DefaultValues = {
    String: "string",
    Int: 12,
    Float: 12.3,
    Boolean: true,
    ID: "xxxx-xxxx-xxxx-xxxx",
    listLength: 3,
};
export type Config = {
    typesFile: string;
    skipTypename: Exclude<RawTypesConfig["skipTypename"], undefined>;
    typesPrefix: Exclude<RawTypesConfig["typesPrefix"], undefined>;
    typesSuffix: Exclude<RawTypesConfig["typesSuffix"], undefined>;
    namingConvention: Exclude<RawTypesConfig["namingConvention"], undefined>;
    maxFieldRecursionDepth: number;
    defaultValues: {
        String: string;
        Int: number;
        Float: number;
        Boolean: boolean;
        ID: string;
        listLength: number;
        // CustomScalar: string;
        CustomScalar?: {
            // Time: "2021-01-01T00:00:00Z";
            [key: string]: string;
        };
    };
};

export function validateConfig(
    rawConfig: unknown,
    outputType: "typescript" | "javascript" = "javascript",
): asserts rawConfig is RawConfig {
    // defaultValues type validations
    if (rawConfig === null || rawConfig === undefined) {
        throw new Error("config.defaultValues must be an object");
    }
    if (typeof rawConfig !== "object") {
        throw new Error("config.defaultValues must be an object");
    }
    if ("maxFieldRecursionDepth" in rawConfig) {
        if (typeof rawConfig.maxFieldRecursionDepth !== "number") {
            throw new Error("config.maxFieldRecursionDepth must be a number");
        }
    }
    if (outputType === "typescript") {
        if (!("typesFile" in rawConfig)) {
            throw new Error("config.typesFile is required");
        }
    }
    if ("defaultValues" in rawConfig) {
        if (typeof rawConfig.defaultValues !== "object") {
            throw new Error("config.defaultValues must be an object");
        }
        const defaultValues = rawConfig.defaultValues as Config["defaultValues"];
        if (defaultValues.String !== undefined && typeof defaultValues.String !== "string") {
            throw new Error("config.defaultValues.String must be a string");
        }
        if (defaultValues.Int !== undefined && typeof defaultValues.Int !== "number") {
            throw new Error("config.defaultValues.Int must be a number");
        }
        if (defaultValues.Float !== undefined && typeof defaultValues.Float !== "number") {
            throw new Error("config.defaultValues.Float must be a number");
        }
        if (defaultValues.Boolean !== undefined && typeof defaultValues.Boolean !== "boolean") {
            throw new Error("config.defaultValues.Boolean must be a boolean");
        }
        if (defaultValues.ID !== undefined && typeof defaultValues.ID !== "string") {
            throw new Error("config.defaultValues.ID must be a string");
        }
        if (
            defaultValues.listLength !== undefined &&
            typeof defaultValues.listLength !== "number"
        ) {
            throw new Error("config.defaultValues.listLength must be a number");
        }
        if (
            defaultValues.CustomScalar !== undefined &&
            typeof defaultValues.CustomScalar !== "object"
        ) {
            throw new Error("config.defaultValues.CustomScalar must be an object");
        }
    }
}

export function normalizeConfig(rawConfig: RawConfig): Config {
    return {
        typesFile: rawConfig.typesFile ?? "",
        skipTypename: rawConfig.skipTypename ?? false,
        typesPrefix: rawConfig.typesPrefix ?? "",
        typesSuffix: rawConfig.typesSuffix ?? "",
        namingConvention: rawConfig.namingConvention ?? "",
        maxFieldRecursionDepth: rawConfig.maxFieldRecursionDepth ?? 3,
        defaultValues: {
            String: rawConfig.defaultValues?.String ?? DefaultValues.String,
            Int: rawConfig.defaultValues?.Int ?? DefaultValues.Int,
            Float: rawConfig.defaultValues?.Float ?? DefaultValues.Float,
            Boolean: rawConfig.defaultValues?.Boolean ?? DefaultValues.Boolean,
            ID: rawConfig.defaultValues?.ID ?? DefaultValues.ID,
            listLength: rawConfig.defaultValues?.listLength ?? DefaultValues.listLength,
            CustomScalar: rawConfig.defaultValues?.CustomScalar ?? {},
        },
    };
}
