import type { RawTypesConfig } from "@graphql-codegen/visitor-plugin-common";

export type RawMockConfig = {
    /**
     * Maximum depth of nested objects when generating mock data.
     * This prevents exponential explosion when generating mock data for deeply nested types.
     * Default is 9.
     */
    maxDepth?: number | undefined;
    /**
     * Maximum number of times a type can be recursively visited.
     * This prevents exponential explosion when generating mock data for recursive types.
     * For example, if User has a field `friends: [User!]!`, setting maxTypeRecursion to 2
     * will allow User -> User -> User but stop there.
     * Default is 2.
     */
    maxTypeRecursion?: number | undefined;
    /**
     * Number of elements to generate for array fields.
     * Default is 3.
     */
    listLength?: number | undefined;
    /**
     * Default values for scalar types.
     */
    defaultValues?:
        | {
              String?: string | undefined;
              Int?: number | undefined;
              Float?: number | undefined;
              Boolean?: boolean | undefined;
              ID?: string | undefined;
              CustomScalar?: {
                  /**
                   * CustomScalar default expression
                   * The value must be an JavaScript expression.
                   * If you want to put a string value, you must put it in quotes
                   * @example
                   * ```js
                   * CustomScalar: {
                   *   Digit: "1",
                   *   DateYYYYMMDD: "'2022-02-03'",
                   *   ISODateTime: "new Date().toISOString()"
                   * }
                   * ```
                   */
                  [key: string]: string;
              };
          }
        | undefined;
};

export type RawConfig = {
    /**
     * path to type definitions file
     * this is generated by client preset
     * e.g. ) "typeFile: "./graphql"
     */
    typesFile?: string | undefined;
    skipTypename?: RawTypesConfig["skipTypename"] | undefined;
    namingConvention?: RawTypesConfig["namingConvention"] | undefined;
    typesPrefix?: RawTypesConfig["typesPrefix"] | undefined;
    typesSuffix?: RawTypesConfig["typesSuffix"] | undefined;
    /**
     * Mock data generation options.
     */
    mock?: RawMockConfig | undefined;
};

export const MockDefaults = {
    maxDepth: 9,
    maxTypeRecursion: 2,
    listLength: 3,
};

export const DefaultValues = {
    String: "string",
    Int: 12,
    Float: 12.3,
    Boolean: true,
    ID: "xxxx-xxxx-xxxx-xxxx",
};

export type MockConfig = {
    maxDepth: number;
    maxTypeRecursion: number;
    listLength: number;
    defaultValues: {
        String: string;
        Int: number;
        Float: number;
        Boolean: boolean;
        ID: string;
        CustomScalar?: {
            [key: string]: string;
        };
    };
};

export type Config = {
    typesFile: string;
    skipTypename: Exclude<RawTypesConfig["skipTypename"], undefined>;
    typesPrefix: Exclude<RawTypesConfig["typesPrefix"], undefined>;
    typesSuffix: Exclude<RawTypesConfig["typesSuffix"], undefined>;
    namingConvention: Exclude<RawTypesConfig["namingConvention"], undefined>;
    mock: MockConfig;
};

export function validateConfig(
    rawConfig: unknown,
    outputType: "typescript" | "javascript" = "javascript",
): asserts rawConfig is RawConfig {
    if (rawConfig === null || rawConfig === undefined) {
        throw new Error("config must be an object");
    }
    if (typeof rawConfig !== "object") {
        throw new Error("config must be an object");
    }
    if (outputType === "typescript") {
        if (!("typesFile" in rawConfig)) {
            throw new Error("config.typesFile is required");
        }
    }
    if ("mock" in rawConfig && rawConfig.mock !== undefined) {
        if (typeof rawConfig.mock !== "object") {
            throw new Error("config.mock must be an object");
        }
        const mock = rawConfig.mock as RawMockConfig;
        if (mock.maxDepth !== undefined && typeof mock.maxDepth !== "number") {
            throw new Error("config.mock.maxDepth must be a number");
        }
        if (mock.maxDepth !== undefined && mock.maxDepth < 1) {
            throw new Error("config.mock.maxDepth must be at least 1");
        }
        if (mock.maxTypeRecursion !== undefined && typeof mock.maxTypeRecursion !== "number") {
            throw new Error("config.mock.maxTypeRecursion must be a number");
        }
        if (mock.maxTypeRecursion !== undefined && mock.maxTypeRecursion < 1) {
            throw new Error("config.mock.maxTypeRecursion must be at least 1");
        }
        if (mock.listLength !== undefined && typeof mock.listLength !== "number") {
            throw new Error("config.mock.listLength must be a number");
        }
        if (mock.defaultValues !== undefined) {
            if (typeof mock.defaultValues !== "object") {
                throw new Error("config.mock.defaultValues must be an object");
            }
            const defaultValues = mock.defaultValues;
            if (defaultValues.String !== undefined && typeof defaultValues.String !== "string") {
                throw new Error("config.mock.defaultValues.String must be a string");
            }
            if (defaultValues.Int !== undefined && typeof defaultValues.Int !== "number") {
                throw new Error("config.mock.defaultValues.Int must be a number");
            }
            if (defaultValues.Float !== undefined && typeof defaultValues.Float !== "number") {
                throw new Error("config.mock.defaultValues.Float must be a number");
            }
            if (defaultValues.Boolean !== undefined && typeof defaultValues.Boolean !== "boolean") {
                throw new Error("config.mock.defaultValues.Boolean must be a boolean");
            }
            if (defaultValues.ID !== undefined && typeof defaultValues.ID !== "string") {
                throw new Error("config.mock.defaultValues.ID must be a string");
            }
            if (
                defaultValues.CustomScalar !== undefined &&
                typeof defaultValues.CustomScalar !== "object"
            ) {
                throw new Error("config.mock.defaultValues.CustomScalar must be an object");
            }
        }
    }
}

export function normalizeConfig(rawConfig: RawConfig): Config {
    return {
        typesFile: rawConfig.typesFile ?? "",
        skipTypename: rawConfig.skipTypename ?? false,
        typesPrefix: rawConfig.typesPrefix ?? "",
        typesSuffix: rawConfig.typesSuffix ?? "",
        namingConvention: rawConfig.namingConvention ?? "",
        mock: {
            maxDepth: rawConfig.mock?.maxDepth ?? MockDefaults.maxDepth,
            maxTypeRecursion: rawConfig.mock?.maxTypeRecursion ?? MockDefaults.maxTypeRecursion,
            listLength: rawConfig.mock?.listLength ?? MockDefaults.listLength,
            defaultValues: {
                String: rawConfig.mock?.defaultValues?.String ?? DefaultValues.String,
                Int: rawConfig.mock?.defaultValues?.Int ?? DefaultValues.Int,
                Float: rawConfig.mock?.defaultValues?.Float ?? DefaultValues.Float,
                Boolean: rawConfig.mock?.defaultValues?.Boolean ?? DefaultValues.Boolean,
                ID: rawConfig.mock?.defaultValues?.ID ?? DefaultValues.ID,
                CustomScalar: rawConfig.mock?.defaultValues?.CustomScalar ?? {},
            },
        },
    };
}
