/* eslint-disable */
// This file was generated by a @newmo/graphql-codegen-fake-server-operation
import type { ListDestinationCandidatesQuery, ListDestinationCandidatesQueryVariables } from './graphql';
import type { ListRideHistoriesQuery, ListRideHistoriesQueryVariables } from './graphql';
import type { CreateUrlRideHistoryMutation, CreateUrlRideHistoryMutationVariables } from './graphql';
import type { CreateFooUrlRideHistoryMutation, CreateFooUrlRideHistoryMutationVariables } from './graphql';

export type FakeClientVariablesConditionRule<TVariables = Record<string, any>> = { type: "variables"; value: TVariables };
export type FakeClientConditionRule<TVariables = Record<string, any>> = FakeClientVariablesConditionRule<TVariables>;

// Single response registration
export type FakeClientRegisterSingleResponse = {
    type: "single";
    operationName: string;
    data: Record<string, unknown>;
};

// Array-based sequence response registration  
export type FakeClientRegisterSequenceResponse = {
    type: "sequence";
    operationName: string;
    data: Record<string, unknown>[];
};

// Conditional response registration
export type FakeClientRegisterConditionalResponse<TVariables = Record<string, any>> = {
    type: "conditional";
    operationName: string;
    conditions: Array<{
        condition: FakeClientConditionRule<TVariables>;
        data: Record<string, unknown> | Record<string, unknown>[];
    }>;
};

// Network error registration
export type FakeClientRegisterNetworkError = {
    type: "network-error";
    operationName: string;
    responseStatusCode: number;
    errors: Record<string, unknown>[];
};

export type FakeClientRegisterSequenceOptions<TVariables = Record<string, any>> = 
    | FakeClientRegisterSingleResponse 
    | FakeClientRegisterSequenceResponse 
    | FakeClientRegisterConditionalResponse<TVariables> 
    | FakeClientRegisterNetworkError;
export type CreateFakeClientOptions = {
  /** 
   * The URL of the fake server
   * @example 'http://localhost:4000/fake'
   */
  fakeServerEndpoint: string;
};
export function createFakeClient(options: CreateFakeClientOptions) {
  if(!options.fakeServerEndpoint.endsWith('/fake')) {
    throw new Error('fakeServerEndpoint must end with "/fake"');
  }
  return {
    async registerListDestinationCandidatesQuery(
        sequenceId: string, 
        data: ListDestinationCandidatesQuery | ListDestinationCandidatesQuery[] | Array<{ condition: FakeClientConditionRule<ListDestinationCandidatesQueryVariables>; data: ListDestinationCandidatesQuery | ListDestinationCandidatesQuery[] }> | { errors: Record<string, unknown>[]; responseStatusCode: number }
    ): Promise<{ ok: true } | { ok: false; errors: string[] }> {
        let requestBody: any;
        
        // Check if it's a network error
        if (typeof data === 'object' && data !== null && 'errors' in data && 'responseStatusCode' in data) {
            requestBody = {
                type: "network-error",
                operationName: "ListDestinationCandidates",
                responseStatusCode: data.responseStatusCode,
                errors: data.errors
            };
        }
        // Check if it's conditional responses
        else if (Array.isArray(data) && data.length > 0 && data[0] && 'condition' in data[0]) {
            requestBody = {
                type: "conditional",
                operationName: "ListDestinationCandidates",
                conditions: data
            };
        }
        // Check if it's sequence responses (array of queries)
        else if (Array.isArray(data)) {
            requestBody = {
                type: "sequence",
                operationName: "ListDestinationCandidates",
                data: data
            };
        }
        // Single response
        else {
            requestBody = {
                type: "single",
                operationName: "ListDestinationCandidates",
                data: data
            };
        }
    
        return await fetch(options.fakeServerEndpoint, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify(requestBody),
        }).then((res) => res.json()) as { ok: true } | { ok: false; errors: string[] };
    },
    async calledListDestinationCandidatesQuery(sequenceId:string): Promise<{
      ok: true;
      data: {
        requestTimestamp: number;
        request: {
          headers: Record<string, unknown>;
          body: {
            operationName: string;
            query: string;
          };
        };
        response: {
            statusCode: number;
            headers: Record<string, unknown>;
            body: ListDestinationCandidatesQuery;
        };
      }[]            
    }> {
        return await fetch(options.fakeServerEndpoint + "/called", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify({
                operationName: "ListDestinationCandidates"
            }),
        }).then((res) => res.json()) as {
      ok: true;
      data: {
        requestTimestamp: number;
        request: {
          headers: Record<string, unknown>;
          body: {
            operationName: string;
            query: string;
          };
        };
        response: {
            statusCode: number;
            headers: Record<string, unknown>;
            body: ListDestinationCandidatesQuery;
        };
      }[];
    };
    },
    async registerListRideHistoriesQuery(
        sequenceId: string, 
        data: ListRideHistoriesQuery | ListRideHistoriesQuery[] | Array<{ condition: FakeClientConditionRule<ListRideHistoriesQueryVariables>; data: ListRideHistoriesQuery | ListRideHistoriesQuery[] }> | { errors: Record<string, unknown>[]; responseStatusCode: number }
    ): Promise<{ ok: true } | { ok: false; errors: string[] }> {
        let requestBody: any;
        
        // Check if it's a network error
        if (typeof data === 'object' && data !== null && 'errors' in data && 'responseStatusCode' in data) {
            requestBody = {
                type: "network-error",
                operationName: "ListRideHistories",
                responseStatusCode: data.responseStatusCode,
                errors: data.errors
            };
        }
        // Check if it's conditional responses
        else if (Array.isArray(data) && data.length > 0 && data[0] && 'condition' in data[0]) {
            requestBody = {
                type: "conditional",
                operationName: "ListRideHistories",
                conditions: data
            };
        }
        // Check if it's sequence responses (array of queries)
        else if (Array.isArray(data)) {
            requestBody = {
                type: "sequence",
                operationName: "ListRideHistories",
                data: data
            };
        }
        // Single response
        else {
            requestBody = {
                type: "single",
                operationName: "ListRideHistories",
                data: data
            };
        }
    
        return await fetch(options.fakeServerEndpoint, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify(requestBody),
        }).then((res) => res.json()) as { ok: true } | { ok: false; errors: string[] };
    },
    async calledListRideHistoriesQuery(sequenceId:string): Promise<{
      ok: true;
      data: {
        requestTimestamp: number;
        request: {
          headers: Record<string, unknown>;
          body: {
            operationName: string;
            query: string;
          };
        };
        response: {
            statusCode: number;
            headers: Record<string, unknown>;
            body: ListRideHistoriesQuery;
        };
      }[]            
    }> {
        return await fetch(options.fakeServerEndpoint + "/called", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify({
                operationName: "ListRideHistories"
            }),
        }).then((res) => res.json()) as {
      ok: true;
      data: {
        requestTimestamp: number;
        request: {
          headers: Record<string, unknown>;
          body: {
            operationName: string;
            query: string;
          };
        };
        response: {
            statusCode: number;
            headers: Record<string, unknown>;
            body: ListRideHistoriesQuery;
        };
      }[];
    };
    },
    async registerCreateUrlRideHistoryMutation(
        sequenceId: string, 
        data: CreateUrlRideHistoryMutation | CreateUrlRideHistoryMutation[] | Array<{ condition: FakeClientConditionRule<CreateUrlRideHistoryMutationVariables>; data: CreateUrlRideHistoryMutation | CreateUrlRideHistoryMutation[] }> | { errors: Record<string, unknown>[]; responseStatusCode: number }
    ): Promise<{ ok: true } | { ok: false; errors: string[] }> {
        let requestBody: any;
        
        // Check if it's a network error
        if (typeof data === 'object' && data !== null && 'errors' in data && 'responseStatusCode' in data) {
            requestBody = {
                type: "network-error",
                operationName: "CreateUrlRideHistory",
                responseStatusCode: data.responseStatusCode,
                errors: data.errors
            };
        }
        // Check if it's conditional responses
        else if (Array.isArray(data) && data.length > 0 && data[0] && 'condition' in data[0]) {
            requestBody = {
                type: "conditional",
                operationName: "CreateUrlRideHistory",
                conditions: data
            };
        }
        // Check if it's sequence responses (array of mutations)
        else if (Array.isArray(data)) {
            requestBody = {
                type: "sequence",
                operationName: "CreateUrlRideHistory",
                data: data
            };
        }
        // Single response
        else {
            requestBody = {
                type: "single",
                operationName: "CreateUrlRideHistory",
                data: data
            };
        }
    
        return await fetch(options.fakeServerEndpoint, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify(requestBody),
        }).then((res) => res.json()) as { ok: true } | { ok: false; errors: string[] };
    },
    async calledCreateUrlRideHistoryMutation(sequenceId:string): Promise<{
      ok: true;
      data: {
        requestTimestamp: number;
        request: {
          headers: Record<string, unknown>;
          body: {
            operationName: string;
            query: string;
            variables: CreateUrlRideHistoryMutationVariables;
          };
        };
        response: {
            statusCode: number;
            headers: Record<string, unknown>;
            body: CreateUrlRideHistoryMutation;
        };
      }[];
    }> {
        return await fetch(options.fakeServerEndpoint + "/called", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify({
                operationName: "CreateUrlRideHistory"
            }),
        }).then((res) => res.json()) as {
      ok: true;
      data: {
        requestTimestamp: number;
        request: {
          headers: Record<string, unknown>;
          body: {
            operationName: string;
            query: string;
            variables: CreateUrlRideHistoryMutationVariables;
          };
        };
        response: {
            statusCode: number;
            headers: Record<string, unknown>;
            body: CreateUrlRideHistoryMutation;
        };
      }[];
    }
    },
    async registerCreateFooUrlRideHistoryMutation(
        sequenceId: string, 
        data: CreateFooUrlRideHistoryMutation | CreateFooUrlRideHistoryMutation[] | Array<{ condition: FakeClientConditionRule<CreateFooUrlRideHistoryMutationVariables>; data: CreateFooUrlRideHistoryMutation | CreateFooUrlRideHistoryMutation[] }> | { errors: Record<string, unknown>[]; responseStatusCode: number }
    ): Promise<{ ok: true } | { ok: false; errors: string[] }> {
        let requestBody: any;
        
        // Check if it's a network error
        if (typeof data === 'object' && data !== null && 'errors' in data && 'responseStatusCode' in data) {
            requestBody = {
                type: "network-error",
                operationName: "CreateFooUrlRideHistory",
                responseStatusCode: data.responseStatusCode,
                errors: data.errors
            };
        }
        // Check if it's conditional responses
        else if (Array.isArray(data) && data.length > 0 && data[0] && 'condition' in data[0]) {
            requestBody = {
                type: "conditional",
                operationName: "CreateFooUrlRideHistory",
                conditions: data
            };
        }
        // Check if it's sequence responses (array of mutations)
        else if (Array.isArray(data)) {
            requestBody = {
                type: "sequence",
                operationName: "CreateFooUrlRideHistory",
                data: data
            };
        }
        // Single response
        else {
            requestBody = {
                type: "single",
                operationName: "CreateFooUrlRideHistory",
                data: data
            };
        }
    
        return await fetch(options.fakeServerEndpoint, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify(requestBody),
        }).then((res) => res.json()) as { ok: true } | { ok: false; errors: string[] };
    },
    async calledCreateFooUrlRideHistoryMutation(sequenceId:string): Promise<{
      ok: true;
      data: {
        requestTimestamp: number;
        request: {
          headers: Record<string, unknown>;
          body: {
            operationName: string;
            query: string;
            variables: CreateFooUrlRideHistoryMutationVariables;
          };
        };
        response: {
            statusCode: number;
            headers: Record<string, unknown>;
            body: CreateFooUrlRideHistoryMutation;
        };
      }[];
    }> {
        return await fetch(options.fakeServerEndpoint + "/called", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify({
                operationName: "CreateFooUrlRideHistory"
            }),
        }).then((res) => res.json()) as {
      ok: true;
      data: {
        requestTimestamp: number;
        request: {
          headers: Record<string, unknown>;
          body: {
            operationName: string;
            query: string;
            variables: CreateFooUrlRideHistoryMutationVariables;
          };
        };
        response: {
            statusCode: number;
            headers: Record<string, unknown>;
            body: CreateFooUrlRideHistoryMutation;
        };
      }[];
    }
    }
  };
}
