/* eslint-disable */
// This file was generated by a @newmo/graphql-codegen-fake-server-operation
import type { ListDestinationCandidatesQuery, ListDestinationCandidatesQueryVariables } from './graphql';
import type { ListRideHistoriesQuery, ListRideHistoriesQueryVariables } from './graphql';
import type { CreateUrlRideHistoryMutation, CreateUrlRideHistoryMutationVariables } from './graphql';
import type { CreateFooUrlRideHistoryMutation, CreateFooUrlRideHistoryMutationVariables } from './graphql';

export type FakeClientAlwaysConditionRule = { type: "always" };
export type FakeClientVariablesConditionRule<TVariables = Record<string, any>> = { type: "variables"; value: TVariables };
export type FakeClientConditionRule<TVariables = Record<string, any>> = FakeClientAlwaysConditionRule | FakeClientVariablesConditionRule<TVariables>;
export type FakeClientRegisterSequenceOptions<TVariables = Record<string, any>> = { requestCondition?: FakeClientConditionRule<TVariables> };
export type CreateFakeClientOptions = {
  /** 
   * The URL of the fake server
   * @example 'http://localhost:4000/fake'
   */
  fakeServerEndpoint: string;
};
export function createFakeClient(options: CreateFakeClientOptions) {
  if(!options.fakeServerEndpoint.endsWith('/fake')) {
    throw new Error('fakeServerEndpoint must end with "/fake"');
  }
  return {
    async registerListDestinationCandidatesQueryResponse(sequenceId:string, queryResponse: ListDestinationCandidatesQuery, sequenceOptions?: FakeClientRegisterSequenceOptions<ListDestinationCandidatesQueryVariables>): Promise<{ ok: true } | { ok: false; errors: string[] }> {
        const requestCondition = sequenceOptions?.requestCondition ?? { type: "always" };
        return await fetch(options.fakeServerEndpoint, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify({
                type: "operation",
                operationName: "ListDestinationCandidates",
                data: queryResponse,
                requestCondition: requestCondition
            }),
        }).then((res) => res.json()) as { ok: true } | { ok: false; errors: string[] };
    },
    async registerListDestinationCandidatesQueryErrorResponse(sequenceId:string, { errors, responseStatusCode }: { errors: Record<string, unknown>[]; responseStatusCode: number }): Promise<{ ok: true } | { ok: false; errors: string[] }> {
        return await fetch(options.fakeServerEndpoint, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify({
                type: "network-error",
                operationName: "ListDestinationCandidates",
                responseStatusCode,
                errors
            }),
        }).then((res) => res.json()) as { ok: true } | { ok: false; errors: string[] };
    },
    async calledListDestinationCandidatesQuery(sequenceId:string): Promise<{
      ok: true;
      data: {
        requestTimestamp: number;
        request: {
          headers: Record<string, unknown>;
          body: {
            operationName: string;
            query: string;
          };
        };
        response: {
            statusCode: number;
            headers: Record<string, unknown>;
            body: ListDestinationCandidatesQuery;
        };
      }[]            
    }> {
        return await fetch(options.fakeServerEndpoint + "/called", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify({
                operationName: "ListDestinationCandidates"
            }),
        }).then((res) => res.json()) as {
      ok: true;
      data: {
        requestTimestamp: number;
        request: {
          headers: Record<string, unknown>;
          body: {
            operationName: string;
            query: string;
          };
        };
        response: {
            statusCode: number;
            headers: Record<string, unknown>;
            body: ListDestinationCandidatesQuery;
        };
      }[];
    };
    },
    async registerListRideHistoriesQueryResponse(sequenceId:string, queryResponse: ListRideHistoriesQuery, sequenceOptions?: FakeClientRegisterSequenceOptions<ListRideHistoriesQueryVariables>): Promise<{ ok: true } | { ok: false; errors: string[] }> {
        const requestCondition = sequenceOptions?.requestCondition ?? { type: "always" };
        return await fetch(options.fakeServerEndpoint, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify({
                type: "operation",
                operationName: "ListRideHistories",
                data: queryResponse,
                requestCondition: requestCondition
            }),
        }).then((res) => res.json()) as { ok: true } | { ok: false; errors: string[] };
    },
    async registerListRideHistoriesQueryErrorResponse(sequenceId:string, { errors, responseStatusCode }: { errors: Record<string, unknown>[]; responseStatusCode: number }): Promise<{ ok: true } | { ok: false; errors: string[] }> {
        return await fetch(options.fakeServerEndpoint, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify({
                type: "network-error",
                operationName: "ListRideHistories",
                responseStatusCode,
                errors
            }),
        }).then((res) => res.json()) as { ok: true } | { ok: false; errors: string[] };
    },
    async calledListRideHistoriesQuery(sequenceId:string): Promise<{
      ok: true;
      data: {
        requestTimestamp: number;
        request: {
          headers: Record<string, unknown>;
          body: {
            operationName: string;
            query: string;
          };
        };
        response: {
            statusCode: number;
            headers: Record<string, unknown>;
            body: ListRideHistoriesQuery;
        };
      }[]            
    }> {
        return await fetch(options.fakeServerEndpoint + "/called", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify({
                operationName: "ListRideHistories"
            }),
        }).then((res) => res.json()) as {
      ok: true;
      data: {
        requestTimestamp: number;
        request: {
          headers: Record<string, unknown>;
          body: {
            operationName: string;
            query: string;
          };
        };
        response: {
            statusCode: number;
            headers: Record<string, unknown>;
            body: ListRideHistoriesQuery;
        };
      }[];
    };
    },
    async registerCreateUrlRideHistoryMutationResponse(sequenceId:string, mutationResponse: CreateUrlRideHistoryMutation, sequenceOptions?: FakeClientRegisterSequenceOptions<CreateUrlRideHistoryMutationVariables>): Promise<{ ok: true } | { ok: false; errors: string[] }> {
        const requestCondition = sequenceOptions?.requestCondition ?? { type: "always" };
        return await fetch(options.fakeServerEndpoint, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify({
                type: "operation",
                operationName: "CreateUrlRideHistory",
                data: mutationResponse,
                requestCondition: requestCondition
            }),
        }).then((res) => res.json()) as { ok: true } | { ok: false; errors: string[] };
    },
    async registerCreateUrlRideHistoryMutationErrorResponse(sequenceId:string, { errors, responseStatusCode }: { errors: Record<string, unknown>[]; responseStatusCode: number }): Promise<{ ok: true } | { ok: false; errors: string[] }> {
        return await fetch(options.fakeServerEndpoint, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify({
                type: "network-error",
                operationName: "CreateUrlRideHistory",
                responseStatusCode,
                errors
            }),
        }).then((res) => res.json()) as { ok: true } | { ok: false; errors: string[] };
    },
    async calledCreateUrlRideHistoryMutation(sequenceId:string): Promise<{
      ok: true;
      data: {
        requestTimestamp: number;
        request: {
          headers: Record<string, unknown>;
          body: {
            operationName: string;
            query: string;
            variables: CreateUrlRideHistoryMutationVariables;
          };
        };
        response: {
            statusCode: number;
            headers: Record<string, unknown>;
            body: CreateUrlRideHistoryMutation;
        };
      }[];
    }> {
        return await fetch(options.fakeServerEndpoint + "/called", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify({
                operationName: "CreateUrlRideHistory"
            }),
        }).then((res) => res.json()) as {
      ok: true;
      data: {
        requestTimestamp: number;
        request: {
          headers: Record<string, unknown>;
          body: {
            operationName: string;
            query: string;
            variables: CreateUrlRideHistoryMutationVariables;
          };
        };
        response: {
            statusCode: number;
            headers: Record<string, unknown>;
            body: CreateUrlRideHistoryMutation;
        };
      }[];
    }
    },
    async registerCreateFooUrlRideHistoryMutationResponse(sequenceId:string, mutationResponse: CreateFooUrlRideHistoryMutation, sequenceOptions?: FakeClientRegisterSequenceOptions<CreateFooUrlRideHistoryMutationVariables>): Promise<{ ok: true } | { ok: false; errors: string[] }> {
        const requestCondition = sequenceOptions?.requestCondition ?? { type: "always" };
        return await fetch(options.fakeServerEndpoint, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify({
                type: "operation",
                operationName: "CreateFooUrlRideHistory",
                data: mutationResponse,
                requestCondition: requestCondition
            }),
        }).then((res) => res.json()) as { ok: true } | { ok: false; errors: string[] };
    },
    async registerCreateFooUrlRideHistoryMutationErrorResponse(sequenceId:string, { errors, responseStatusCode }: { errors: Record<string, unknown>[]; responseStatusCode: number }): Promise<{ ok: true } | { ok: false; errors: string[] }> {
        return await fetch(options.fakeServerEndpoint, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify({
                type: "network-error",
                operationName: "CreateFooUrlRideHistory",
                responseStatusCode,
                errors
            }),
        }).then((res) => res.json()) as { ok: true } | { ok: false; errors: string[] };
    },
    async calledCreateFooUrlRideHistoryMutation(sequenceId:string): Promise<{
      ok: true;
      data: {
        requestTimestamp: number;
        request: {
          headers: Record<string, unknown>;
          body: {
            operationName: string;
            query: string;
            variables: CreateFooUrlRideHistoryMutationVariables;
          };
        };
        response: {
            statusCode: number;
            headers: Record<string, unknown>;
            body: CreateFooUrlRideHistoryMutation;
        };
      }[];
    }> {
        return await fetch(options.fakeServerEndpoint + "/called", {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'sequence-id': sequenceId
            },
            body: JSON.stringify({
                operationName: "CreateFooUrlRideHistory"
            }),
        }).then((res) => res.json()) as {
      ok: true;
      data: {
        requestTimestamp: number;
        request: {
          headers: Record<string, unknown>;
          body: {
            operationName: string;
            query: string;
            variables: CreateFooUrlRideHistoryMutationVariables;
          };
        };
        response: {
            statusCode: number;
            headers: Record<string, unknown>;
            body: CreateFooUrlRideHistoryMutation;
        };
      }[];
    }
    }
  };
}
