/* eslint-disable */
// This file was generated by a @newmo/graphql-codegen-fake-server-operation
import type { ListDestinationCandidatesQuery } from './graphql';
import type { ListRideHistoriesQuery } from './graphql';
import type { CreateRideHistoryMutation } from './graphql';
export async function registerListDestinationCandidatesQueryResponse(sequenceId:string, queryResponse: ListDestinationCandidatesQuery): Promise<{ ok: true } | { ok: false; errors: string[] }> {
    return await fetch('http://127.0.0.1:4000/register-operation', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'sequence-id': sequenceId
        },
        body: JSON.stringify({
            type: "operation",
            operationName: "ListDestinationCandidates",
            data: queryResponse
        }),
    }).then((res) => res.json()) as { ok: true } | { ok: false; errors: string[] };
}
export async function registerListDestinationCandidatesQueryErrorResponse(sequenceId:string, { errors, responseStatusCode }: { errors: Record<string, unknown>[]; responseStatusCode: number }): Promise<{ ok: true } | { ok: false; errors: string[] }> {
    return await fetch('http://127.0.0.1:4000/register-operation', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'sequence-id': sequenceId
        },
        body: JSON.stringify({
            type: "network-error",
            operationName: "ListDestinationCandidates",
            responseStatusCode,
            errors
        }),
    }).then((res) => res.json()) as { ok: true } | { ok: false; errors: string[] };
}
export async function registerListRideHistoriesQueryResponse(sequenceId:string, queryResponse: ListRideHistoriesQuery): Promise<{ ok: true } | { ok: false; errors: string[] }> {
    return await fetch('http://127.0.0.1:4000/register-operation', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'sequence-id': sequenceId
        },
        body: JSON.stringify({
            type: "operation",
            operationName: "ListRideHistories",
            data: queryResponse
        }),
    }).then((res) => res.json()) as { ok: true } | { ok: false; errors: string[] };
}
export async function registerListRideHistoriesQueryErrorResponse(sequenceId:string, { errors, responseStatusCode }: { errors: Record<string, unknown>[]; responseStatusCode: number }): Promise<{ ok: true } | { ok: false; errors: string[] }> {
    return await fetch('http://127.0.0.1:4000/register-operation', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'sequence-id': sequenceId
        },
        body: JSON.stringify({
            type: "network-error",
            operationName: "ListRideHistories",
            responseStatusCode,
            errors
        }),
    }).then((res) => res.json()) as { ok: true } | { ok: false; errors: string[] };
}
export async function registerCreateRideHistoryMutationResponse(sequenceId:string, mutationResponse: CreateRideHistoryMutation): Promise<{ ok: true } | { ok: false; errors: string[] }> {
    return await fetch('http://127.0.0.1:4000/register-operation', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'sequence-id': sequenceId
        },
        body: JSON.stringify({
            type: "operation",
            operationName: "CreateRideHistory",
            data: mutationResponse
        }),
    }).then((res) => res.json()) as { ok: true } | { ok: false; errors: string[] };
}
export async function registerCreateRideHistoryMutationErrorResponse(sequenceId:string, { errors, responseStatusCode }: { errors: Record<string, unknown>[]; responseStatusCode: number }): Promise<{ ok: true } | { ok: false; errors: string[] }> {
    return await fetch('http://127.0.0.1:4000/register-operation', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'sequence-id': sequenceId
        },
        body: JSON.stringify({
            type: "network-error",
            operationName: "CreateRideHistory",
            responseStatusCode,
            errors
        }),
    }).then((res) => res.json()) as { ok: true } | { ok: false; errors: string[] };
}
