import { convertFactory, ConvertFn, RawTypesConfig } from "@graphql-codegen/visitor-plugin-common";

export type RawConfig = {
    /**
     * path to type definitions file
     * this is generated by client preset
     * e.g. ) "typeFile: "./graphql"
     */
    typesFile?: string;
    skipTypename?: RawTypesConfig['skipTypename'];
    namingConvention?: RawTypesConfig['namingConvention'];
    typesPrefix?: RawTypesConfig['typesPrefix'];
    typesSuffix?: RawTypesConfig['typesSuffix'];
    maxFieldRecursionDepth?: number;
    defaultValues?: {
        String?: string
        Int?: number
        Float?: number
        Boolean?: boolean
        ID?: string
        listLength?: number
    }
};

export const DefaultValues = {
    String: "string",
    Int: 12,
    Float: 12.3,
    Boolean: true,
    ID: "xxxx-xxxx-xxxx-xxxx",
    listLength: 3
}
export type Config = {
    typesFile: string;
    skipTypename: Exclude<RawTypesConfig['skipTypename'], undefined>;
    typesPrefix: Exclude<RawTypesConfig['typesPrefix'], undefined>;
    typesSuffix: Exclude<RawTypesConfig['typesSuffix'], undefined>;
    convert: ConvertFn;
    maxFieldRecursionDepth: number;
    defaultValues: {
        String: string
        Int: number
        Float: number
        Boolean: boolean
        ID: string,
        listLength: number
    }
};

export function validateConfig(rawConfig: unknown, outputType: "typescript" | "javascript" = "javascript"): asserts rawConfig is RawConfig {
    // defaultValues type validations
    if (rawConfig === null || rawConfig === undefined) {
        throw new Error(`config.defaultValues must be an object`);
    }
    if (typeof rawConfig !== "object") {
        throw new Error(`config.defaultValues must be an object`);
    }
    if ("maxFieldRecursionDepth" in rawConfig) {
        if (typeof rawConfig.maxFieldRecursionDepth !== "number") {
            throw new Error(`config.maxFieldRecursionDepth must be a number`);
        }
    }
    if (outputType) {
        if (!("typesFile" in rawConfig)) {
            throw new Error(`config.typesFile is required`);
        }
    }
    if ("defaultValues" in rawConfig) {
        if (typeof rawConfig.defaultValues !== "object") {
            throw new Error(`config.defaultValues must be an object`);
        }
        const defaultValues = rawConfig.defaultValues as Config["defaultValues"];
        if (defaultValues.String !== undefined && typeof defaultValues.String !== "string") {
            throw new Error(`config.defaultValues.String must be a string`);
        }
        if (defaultValues.Int !== undefined && typeof defaultValues.Int !== "number") {
            throw new Error(`config.defaultValues.Int must be a number`);
        }
        if (defaultValues.Float !== undefined && typeof defaultValues.Float !== "number") {
            throw new Error(`config.defaultValues.Float must be a number`);
        }
        if (defaultValues.Boolean !== undefined && typeof defaultValues.Boolean !== "boolean") {
            throw new Error(`config.defaultValues.Boolean must be a boolean`);
        }
        if (defaultValues.ID !== undefined && typeof defaultValues.ID !== "string") {
            throw new Error(`config.defaultValues.ID must be a string`);
        }
        if (defaultValues.listLength !== undefined && typeof defaultValues.listLength !== "number") {
            throw new Error(`config.defaultValues.listLength must be a number`);
        }
    }
}

export function normalizeConfig(rawConfig: RawConfig): Config {
    return {
        typesFile: rawConfig.typesFile ?? "",
        skipTypename: rawConfig.skipTypename ?? false,
        typesPrefix: rawConfig.typesPrefix ?? "",
        typesSuffix: rawConfig.typesSuffix ?? "",
        convert: rawConfig.namingConvention
            ? convertFactory({ namingConvention: rawConfig.namingConvention })
            : convertFactory({}),
        maxFieldRecursionDepth: rawConfig.maxFieldRecursionDepth ?? 3,
        defaultValues: {
            String: rawConfig.defaultValues?.String ?? DefaultValues.String,
            Int: rawConfig.defaultValues?.Int ?? DefaultValues.Int,
            Float: rawConfig.defaultValues?.Float ?? DefaultValues.Float,
            Boolean: rawConfig.defaultValues?.Boolean ?? DefaultValues.Boolean,
            ID: rawConfig.defaultValues?.ID ?? DefaultValues.ID,
            listLength: rawConfig.defaultValues?.listLength ?? DefaultValues.listLength
        }
    };
}
