# =============================================================================
# Directives
# =============================================================================

"""
@exampleID directive specifies an example value for a ID field.
This example value is used in the fake data.
ID value will be unique between all ID fake data.
"""
directive @exampleID(
    """
    The value of the ID field.
    @exampleID(value: "id")
    """
    value: ID!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
"""
@exampleString directive specifies an example value for a String field.
This example value is used in the fake data.
"""
directive @exampleString(
    """
    The value of the String field.
    @exampleString(value: "example")
    """
    value: String!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
"""
@exampleInt directive specifies an example value for a Int field.
This example value is used in the fake data.
"""
directive @exampleInt(
    """
    The value of the Int field.
    @exampleInt(value: 1)
    """
    value: Int!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
"""
@exampleFloat directive specifies an example value for a Float field.
This example value is used in the fake data.
"""
directive @exampleFloat(
    """
    The value of the Float field.
    @exampleFloat(value: 1.0)
    """
    value: Float!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
"""
@exampleBoolean directive specifies an example value for a Boolean field.
This example value is used in the fake data.
"""
directive @exampleBoolean(
    """
    The value of the Boolean field.
    @exampleBoolean(value: true)
    """
    value: Boolean!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION

"""
@exampleArrayID directive specifies an example value for a array of ID field.
This example value is used in the fake data.
ID value will be unique between all ID fake data.
"""
directive @exampleArrayID(
    """
    The value of the ID field.
    @exampleArrayID(value: ["id1", "id2"])
    """
    values: [ID!]!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
"""
@exampleArrayString directive specifies an example value for a array of String field.
This example value is used in the fake data.
"""
directive @exampleArrayString(
    """
    The value of the String field.
    @exampleArrayString(value: ["example1", "example2"])
    """
    values: [String!]!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
"""
@exampleArrayInt directive specifies an example value for a array of Int field.
This example value is used in the fake data.
"""
directive @exampleArrayInt(
    """
    The value of the Int field.
    @exampleArrayInt(value: [1, 2])
    """
    values: [Int!]!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
"""
@exampleArrayFloat directive specifies an example value for a array of Float field.
This example value is used in the fake data.
"""
directive @exampleArrayFloat(
    """
    The value of the Float field.
    @exampleArrayFloat(value: [1.0, 2.0])
    """
    values: [Float!]!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
"""
@exampleArrayBoolean directive specifies an example value for a array of Boolean field.
This example value is used in the fake data.
"""
directive @exampleArrayBoolean(
    """
    The value of the Boolean field.
    @exampleArrayBoolean(value: [true, false])
    """
    values: [Boolean!]!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
"""
@exampleScalarString directive specifies an example value for a scalar field.
This example value is used in the fake data.
"""
directive @exampleScalarString(
    """
    The value of the scalar field.
    scalar CustomString @exampleScalar(value: "example")
    """
    value: String!
) on SCALAR
"""
@exampleScalarInt directive specifies an example value for a scalar field.
This example value is used in the fake data.
"""
directive @exampleScalarInt(
    """
    The value of the scalar field.
    scalar CustomValue @exampleScalar(value: 1)
    """
    value: Int!
) on SCALAR
"""
@exampleScalarFloat directive specifies an example value for a scalar field.
This example value is used in the fake data.
"""
directive @exampleScalarFloat(
    """
    The value of the scalar field.
    scalar CustomValue @exampleScalar(value: 1.0)
    """
    value: Float!
) on SCALAR
"""
@exampleScalarBoolean directive specifies an example value for a scalar field.
This example value is used in the fake data.
"""
directive @exampleScalarBoolean(
    """
    The value of the scalar field.
    scalar CustomValue @exampleScalar(value: true)
    """
    value: Boolean!
) on SCALAR
"""
@error directive specifies a field as an error response field.
It allows setting an error response and specifying the field name.
"""
directive @error on FIELD_DEFINITION

# =============================================================================
# Scalars
# =============================================================================

# This scalar example value is defined in graphql-fake.config.mjs
scalar DATE_YYYYMMDD
# This scalar example value is defined by @exampleScalarString directive
scalar DATE_YYYYMM @exampleScalarString(value: "2022-01")

# =============================================================================
# Book / Author
# =============================================================================

enum BookGenre {
    FICTION
    NON_FICTION
}
type Book {
    id: ID! @exampleID(value: "book-id")
    title: String! @exampleString(value: "The Great Gatsby")
    author: Author!
    genre: BookGenre! @exampleString(value: "FICTION")
    genre_non_example: BookGenre!
}
type Author {
    id: ID! @exampleID(value: "author-id")
    name: String! @exampleString(value: "F. Scott Fitzgerald")
    age: Int! @exampleInt(value: 33)
    books: [Book!]!
}
input CreateBookInput {
    title: String! @exampleString(value: "input title")
}

# =============================================================================
# User / Union
# =============================================================================

type UserNamesArrayExample {
    names: [String!]! @exampleArrayString(values: ["name1", "name2"])
}
type User {
    id: ID!
    name: String
    birthDate: DATE_YYYYMMDD
    birthYYYYMM: DATE_YYYYMM
}
type UserSuspended {
    reason: String
}
type UserIsBlocked {
    message: String
    blockedByUser: User
}
type UserWithErrors {
    id: ID!
    name: String!
    errors: [GeneralError!]! @error
}
union UnionUserResult = User | UserSuspended | UserIsBlocked

# =============================================================================
# Character / Interface
# =============================================================================

interface Character {
    id: ID!
    name: String!
}
type Dog implements Character {
    id: ID!
    name: String!
    nickname: String!
}

# =============================================================================
# Error Interfaces
# =============================================================================

interface Error {
    message: String!
}
interface DisplayableError {
    message: String!
    code: AbcErrorCode!
    localizedMessage: String!
}

# =============================================================================
# Mutation Error Pattern
# https://productionreadygraphql.com/2020-08-01-guide-to-graphql-errors
# https://speakerdeck.com/yukukotani/graphql-schema-design-practice?slide=23
# =============================================================================

input UseMutationErrorPatternInput {
    id: String!
}
type MutationErrorPattern {
    id: ID!
    name: String
}
type UseMutationErrorPatternPayload {
    MutationErrorPattern: MutationErrorPattern
    errors: [UseMutationErrorPatternError!]!
}
union UseMutationErrorPatternError = GeneralError | AbcError
type GeneralError implements Error {
    message: String!
}
type AbcError implements Error & DisplayableError {
    message: String!
    code: AbcErrorCode!
    localizedMessage: String!
}
enum AbcErrorCode {
    INVALID
    ALREADY_EXIST
}

# =============================================================================
# FooURL (Case Sensitivity Test)
# =============================================================================

type FooURLResource {
    "Foo URL"
    URL: String!
}
input FooURLInput {
    "Foo URL"
    URL: String!
}
type FooURLPayload {
    "Foo URL"
    URL: String!
    "Errors"
    errors: [CreateFooURLError!]!
}
union CreateFooURLError = CreateFooURLErrorDetail
type CreateFooURLErrorDetail implements Error {
    code: CreateFooURLErrorCode!
    message: String!
}
enum CreateFooURLErrorCode {
    FAILED_TO_CREATE_FOO_URL
}

# =============================================================================
# SimpleUnion
# =============================================================================

"Union type that always returns the first concrete type (First)"
union SimpleUnion = First | Second | Third
type First {
    value: String! @exampleString(value: "first-value")
}
type Second {
    value: String! @exampleString(value: "second-value")
}
type Third {
    value: String! @exampleString(value: "third-value")
}

# =============================================================================
# Root Types
# =============================================================================

type Query {
    author(id: ID!): Author
    authors: [Author!]!
    book(id: ID!): Book
    books: [Book!]!
    dog: Dog!
    simpleUnion: SimpleUnion
    unionUser: UnionUserResult
    userNamesArray: UserNamesArrayExample!
    userWithErrors: UserWithErrors
}

type Mutation {
    createBook(input: CreateBookInput!): Book!
    createBookInline(
        bookId: ID! @exampleID(value: "id")
        bookTitle: String! @exampleString(value: "input title")
    ): Book!
    useMutationErrorPattern(input: UseMutationErrorPatternInput!): UseMutationErrorPatternPayload!
    createFooURL(input: FooURLInput!): FooURLPayload!
}
