"""
@exampleID directive specifies an example value for a ID field.
This example value is used in the fake data.
ID value will be unique between all ID fake data.
"""
directive @exampleID(
    """
    The value of the ID field.
    @exampleID(value: "id")
    """
    value: ID!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
"""
@exampleString directive specifies an example value for a String field.
This example value is used in the fake data.
"""
directive @exampleString(
    """
    The value of the String field.
    @exampleString(value: "example")
    """
    value: String!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
"""
@exampleInt directive specifies an example value for a Inf field.
This example value is used in the fake data.
"""
directive @exampleInt(
    """
    The value of the Int field.
    @exampleInt(value: 1)
    """
    value: Int!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
"""
@exampleFloat directive specifies an example value for a Float field.
This example value is used in the fake data.
"""
directive @exampleFloat(
    """
    The value of the Float field.
    @exampleFloat(value: 1.0)
    """
    value: Float!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
"""
@exampleBoolean directive specifies an example value for a Boolean field.
This example value is used in the fake data.
"""
directive @exampleBoolean(
    """
    The value of the Boolean field.
    @exampleBoolean(value: true)
    """
    value: Boolean!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION

"""
@exampleArrayID directive specifies an example value for a array of ID field.
This example value is used in the fake data.
ID value will be unique between all ID fake data.
"""
directive @exampleArrayID(
    """
    The value of the ID field.
    @exampleArrayID(value: ["id1", "id2"])
    """
    value: [ID!]!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
"""
@exampleArrayString directive specifies an example value for a array of String field.
This example value is used in the fake data.
"""
directive @exampleArrayString(
    """
    The value of the String field.
    @exampleArrayString(value: ["example1", "example2"])
    """
    value: [String!]!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
"""
@exampleArrayInt directive specifies an example value for a array of Int field.
This example value is used in the fake data.
"""
directive @exampleArrayInt(
    """
    The value of the Int field.
    @exampleArrayInt(value: [1, 2])
    """
    value: [Int!]!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
"""
@exampleArrayFloat directive specifies an example value for a array of Float field.
This example value is used in the fake data.
"""
directive @exampleArrayFloat(
    """
    The value of the Float field.
    @exampleArrayFloat(value: [1.0, 2.0])
    """
    value: [Float!]!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION
"""
@exampleArrayBoolean directive specifies an example value for a array of Boolean field.
This example value is used in the fake data.
"""
directive @exampleArrayBoolean(
    """
    The value of the Boolean field.
    @exampleArrayBoolean(value: [true, false])
    """
    value: [Boolean!]!
) on FIELD_DEFINITION | ARGUMENT_DEFINITION | INPUT_FIELD_DEFINITION

"""
You Schema definition goes here
"""
enum BookGenre {
    FICTION
    NON_FICTION
}
type Book {
    id: ID! @exampleID(value: "book-id")
    title: String! @exampleString(value: "The Great Gatsby")
    author: Author!
    genre: BookGenre! @exampleString(value: "FICTION")
    genre_non_example: BookGenre!
}
type Author {
    id: ID! @exampleID(value: "author-id")
    name: String! @exampleString(value: "F. Scott Fitzgerald")
    age: Int! @exampleInt(value: 33)
    books: [Book!]!
}

# Interface for errors
interface Character {
    id: ID!
    name: String!
}
type Dog implements Character {
    id: ID!
    name: String!
    nickname: String!
}
# union types
type User {
    id: ID!
    name: String
}
type UserSuspended {
    reason: String
}
type UserIsBlocked {
    message: String
    blockedByUser: User
}
union UnionUserResult = User | UserSuspended | UserIsBlocked

type Query {
    author(id: ID!): Author
    authors: [Author!]!
    book(id: ID!): Book
    books: [Book!]! @exampleArrayString(value:1)
    dog: Dog!
    unionUser: UnionUserResult
}

input CreateBookInput {
    title: String! @exampleString(value: "input title")
}

type Mutation {
    createBook(input: CreateBookInput!): Book!
    createBookInline(bookId: ID! @exampleID(value: "id"), bookTitle:String! @exampleString(value: "input title")): Book!
}
