query GetBooks {
    books {
        id
        title
    }
}
# Fragment
fragment BookFragmentParts on Book {
    id
    title
}
query GetBookWithFragments($bookId: ID!) {
    book(id: $bookId) {
        ...BookFragmentParts
    }
}
query GetDog {
    dog {
        id
        name
    }
}

query GotUnionUser {
    unionUser {
        ... on User {
            id
            name
        }
        ... on UserIsBlocked {
            message
            blockedByUser {
                id
                name
            }
        }
    }
}

mutation CreateBook($title: String!) {
    createBook(input: { title: $title }) {
        id
        title
    }
}

mutation CreateBookInline($title: String!) {
    createBookInline(bookId: 1, bookTitle: $title) {
        id
        title
    }
}

