query GetBooks {
    books {
        id
        title
    }
}
# Fragment
fragment BookFragmentParts on Book {
    id
    title
}
query GetBookWithFragments($bookId: ID!) {
    book(id: $bookId) {
        ...BookFragmentParts
    }
}
query GetDog {
    dog {
        id
        name
    }
}

query GotUnionUser {
    unionUser {
        ... on User {
            id
            name
            birthDate
        }
        ... on UserIsBlocked {
            message
            blockedByUser {
                id
                name
            }
        }
    }
}

query GetUserNamesArrayExample{
    userNamesArray {
        names
    }
}

mutation CreateBook($title: String!) {
    createBook(input: { title: $title }) {
        id
        title
    }
}

mutation CreateBookInline($title: String!) {
    createBookInline(bookId: 1, bookTitle: $title) {
        id
        title
    }
}


# errors pattern
mutation UseMutationErrorPatternMutation {
    useMutationErrorPattern(input: {
        id: "x"
    }) {
        errors {
            ... on GeneralError {
                message
            }
            ... on AbcError {
                message
                code
                localizedMessage
            }
            ... on DisplayableError {
                localizedMessage
                message
            }
            ... on Error {
                message
            }
        }
    }
}

# mutation createFooURL
mutation CreateFooURL ($input: FooURLInput!) {
    createFooURL(input: $input) {
        URL
        errors {
            ... on CreateFooURLErrorDetail{
                code
                message
            }
        }
    }
}
