import type { CodegenPlugin } from "@graphql-codegen/plugin-helpers";

export type PluginConfig = {
    /**
     * The path to the generated types file
     * @example
     * typeFile: "./graphql.ts"
     **/
    typesFile: string;
    /**
     * The URL of the fake server
     * Default: 'http://localhost:4000/graphql'
     */
    fakeServerUrl: string;
};
const plugin: CodegenPlugin<PluginConfig> = {
    plugin(schema, documents, config, _info) {
        const fakeServerUrl = config.fakeServerUrl || "http://localhost:4000/register-operation";
        const registerOperationResponseType = "{ ok: true } | { ok: false; errors: string[] }";
        const generateRegisterOperation = (name: string) => {
            return `export async function register${name}QueryResponse(sequenceId:string, queryResponse: ${name}Query): Promise<${registerOperationResponseType}> {
    return await fetch('${fakeServerUrl}', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'sequence-id': sequenceId
        },
        body: JSON.stringify({
            type: "operation",
            operationName: "${name}",
            data: queryResponse
        }),
    }).then((res) => res.json()) as ${registerOperationResponseType};
}`;
        };
        const generateRegisterOperationError = (name: string) => {
            return `export async function register${name}QueryErrorResponse(sequenceId:string, { errors, responseStatusCode }: { errors: Record<string, unknown>[]; responseStatusCode: number }): Promise<${registerOperationResponseType}> {
    return await fetch('${fakeServerUrl}', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'sequence-id': sequenceId
        },
        body: JSON.stringify({
            type: "network-error",
            operationName: "${name}",
            responseStatusCode,
            errors
        }),
    }).then((res) => res.json()) as ${registerOperationResponseType};
}`;
        };
        const generateRegisterMutation = (name: string) => {
            return `export async function register${name}MutationResponse(sequenceId:string, mutationResponse: ${name}Mutation): Promise<${registerOperationResponseType}> {
    return await fetch('${fakeServerUrl}', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'sequence-id': sequenceId
        },
        body: JSON.stringify({
            type: "operation",
            operationName: "${name}",
            data: mutationResponse
        }),
    }).then((res) => res.json()) as ${registerOperationResponseType};
}`;
        };
        const generateRegisterMutationError = (name: string) => {
            return `export async function register${name}MutationErrorResponse(sequenceId:string, { errors, responseStatusCode }: { errors: Record<string, unknown>[]; responseStatusCode: number }): Promise<${registerOperationResponseType}> {
    return await fetch('${fakeServerUrl}', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'sequence-id': sequenceId
        },
        body: JSON.stringify({
            type: "network-error",
            operationName: "${name}",
            responseStatusCode,
            errors
        }),
    }).then((res) => res.json()) as ${registerOperationResponseType};
}`;
        };
        const importQueryIdentifierName = (documentName: string) => {
            return `import type { ${documentName}Query } from '${config.typesFile}';`;
        };
        const importMutationIdentifierName = (documentName: string) => {
            return `import type { ${documentName}Mutation } from '${config.typesFile}';`;
        };
        return `/* eslint-disable */
// This file was generated by a @newmo/graphql-codegen-fake-server-operation
${documents
    .flatMap((document) => {
        return document.document?.definitions?.map((definition) => {
            // query
            if (
                definition.kind === "OperationDefinition" &&
                definition.operation === "query" &&
                definition.name
            ) {
                return importQueryIdentifierName(definition.name.value);
            }
            if (
                definition.kind === "OperationDefinition" &&
                definition.operation === "mutation" &&
                definition.name
            ) {
                return importMutationIdentifierName(definition.name.value);
            }
            return [];
        });
    })
    .join("\n")}
${documents
    .flatMap((document) => {
        return document.document?.definitions?.flatMap((definition) => {
            // query
            if (
                definition.kind === "OperationDefinition" &&
                definition.operation === "query" &&
                definition.name
            ) {
                return [
                    generateRegisterOperation(definition.name.value),
                    generateRegisterOperationError(definition.name.value),
                ];
            }
            if (
                definition.kind === "OperationDefinition" &&
                definition.operation === "mutation" &&
                definition.name
            ) {
                return [
                    generateRegisterMutation(definition.name.value),
                    generateRegisterMutationError(definition.name.value),
                ];
            }
            return [];
        });
    })
    .join("\n")}
`;
    },
};
// GraphQL Codegen Plugin requires CommonJS export
module.exports = plugin;
